#!/bin/bash

CHEMIN="$HOME/PPE-2025/Exercice1/ann"


if [ $# -ne 0 ]
then
    echo "probleme ! "
    exit
fi

for ANNEE in 2016 2017 2018
do
    echo "Nombre de lieux en $ANNEE"
    grep "Location" "$CHEMIN/$ANNEE"/*/*.ann | wc -l

done


