#!/usr/bin/bash
#on rend ce scripte executable en bash, bin = binaire, , usr = unix systeme resources
if [ $# -ne 1 ] #condition = [ nombre de parametre -ne = diff de 1]
then
echo " ce programme demande un argument " #imprime le string""
exit #sortie
fi #finde la condition
FICHIER_URLS=$1 #premier arg
OK=0 #attribution valeur aux variables
NOK=0
while read -r LINE ; #boucle while lit une ligne, -r = empeche interpretation'\' line = nom de la variable
do
echo " la ligne : $LINE " #imprime le string
if [[ $LINE =∼ ^https?:// ]] #condition si la ligne contient les caractres suivants
then
echo " ressemble à une URL valide " #resultat = url valid
OK=$( expr $OK + 1) #comptabilise en +1
else #sinon
echo " ne ressemble pas à une URL valide " #pas valid
NOK=$( expr $NOK + 1) #comptabilise nok
fi # fin de la condition
done < $FICHIER_URLS # fin boucle while
echo " $OK URLs et $NOK lignes douteuses "
#imprime le texte

#je pense que ce code permet de parcourir une liste de URL dans un fichier et de dire si oui ou non c'est un URL valid, et de les comptabiliser
