#!/bin/bash

fichier=$1
nbligne=1

if [ $# -ne 1 ]
    then
    echo "le script attend exactement un argument: le chemin vers le fichier d'url. "
    exit
fi

echo  "<table><tr> <th>nombre de lignes</th><th>URL</th><th>code_HTTP</th><th>charset</th><th>nombre de mots</th><th>mot_occurence</th><th>pasges_aspirées</th><th>dump_initiale</th><th>dump-UTF8</th></tr>"> orientalismefr.html;


while read -r url ;
do
    curl $url > "Aspirations/fr-$indice.html"
    error_code=$?
    #ENCODAGE=$(curl -s -o /dev/null -w '%{content_type}' "$url")
    encodage=$(file --mime-encoding --brief "Aspirations/fr-$indice.html")
#     echo $encodage
    if [[ $encodage == 'utf-8' ]]
        then
        lynx "Aspirations/fr-$indice.html" -dump -nolist > "dump-text/fr-$indice.txt"
    else

        iconv -f $encodage -t UTF-8 | lynx -stdin -dump -nolist > "dump-text/fr-$indice.txt"
    fi
    #HTTP=$(curl -s -o /dev/null -w '%{http_code}' "$line")
    MOTS=$( wc -w "dump-text/fr-$indice.txt")
    ORIENTALISME_OCCURRENCE=$( grep -E '(^Orient| orient)' "dump-text/fr-$indice.txt"| wc -w)
    echo -e "<tr>
        <td>$indice</td>
        <td>${url}</td>
        <td>$error_code</td>
        <td>$encodage</td>
        <td>$MOTS</td>
        <td>$ORIENTALISME_OCCURRENCE</td>
        <td><a href='Aspirations/fr-$indice.html'>$indice.html</a></td>
        <td><a href='dump-text/fr-$indice.txt'>$indice.txt</a></td></tr>" >>orientalismefr.html;

    indice=$( expr $indice + 1);
done < $fichier;

echo "</table>" >>orientalismefr.html;
